server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bus_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      INDENT_OUTPUT: true
cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_ACCESS_KEY}
    region:
      static: ap-southeast-2
    s3:
      bucket: bus-app-images
