server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  # T?m th?i dùng update cho phát tri?n
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  secret: your-super-secret-key  # Dùng ?? ký JWT
  expiration: 2592000  # 1 ngày = 86,400,000 ms
