server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  expiration: 2592000
  #30 day = 30d * 24h * 60m * 60s
  secretKey: lQn3Thi49pHqTcOfYiHGN6sdBao+T4Ss/wEIER0ZDMQ=
